# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('school', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')])),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Sports'), (1, 'Others')], default=0)),
                ('name_en', models.CharField(max_length=30)),
                ('name_kr', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('winner', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')], default=0)),
                ('location', models.IntegerField()),
                ('score_KAIST', models.IntegerField(default=0)),
                ('score_POSTECH', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=30)),
                ('name_kr', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('score_baseball_KAIST', models.IntegerField()),
                ('score_baseball_POSTECH', models.IntegerField()),
                ('score_basketball_KAIST', models.IntegerField()),
                ('score_basketball_POSTECH', models.IntegerField()),
                ('score_esports_KAIST', models.IntegerField()),
                ('score_esports_POSTECH', models.IntegerField()),
                ('score_soccer_KAIST', models.IntegerField()),
                ('score_soccer_POSTECH', models.IntegerField()),
                ('winner_basketball', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')])),
                ('winner_baseball', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')])),
                ('winner_esports', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')])),
                ('winner_soccer', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')])),
                ('winner_quiz', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')])),
                ('winner_AI', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')])),
                ('winner_hacking', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')])),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='players_KAIST',
            field=models.ManyToManyField(related_name='player_kaist', to='core.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='players_POSTECH',
            field=models.ManyToManyField(related_name='player_postech', to='core.Player'),
        ),
        migrations.AddField(
            model_name='cheermessage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
    ]
