# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name_kr',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name_en',
        ),
    ]
