# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170722_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIToto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BaseballToto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_k', models.IntegerField()),
                ('score_p', models.IntegerField()),
                ('winner', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballToto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_k', models.IntegerField()),
                ('score_p', models.IntegerField()),
                ('winner', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EsportsToto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_k', models.IntegerField()),
                ('score_p', models.IntegerField()),
                ('winner', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HackingToto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuizToto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SoccerToto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_k', models.IntegerField()),
                ('score_p', models.IntegerField()),
                ('winner', models.IntegerField(choices=[(0, 'NONE'), (1, 'KAIST'), (2, 'POSTECH')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='score_baseball_k',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='score_baseball_p',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='score_basketball_k',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='score_basketball_p',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='score_esports_k',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='score_esports_p',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='score_soccer_k',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='score_soccer_p',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='winner_AI',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='winner_baseball',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='winner_basketball',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='winner_esports',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='winner_hacking',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='winner_quiz',
        ),
        migrations.RemoveField(
            model_name='totocontent',
            name='winner_soccer',
        ),
        migrations.AddField(
            model_name='event',
            name='live',
            field=models.IntegerField(choices=[(0, 'Pre'), (1, 'Live'), (2, 'Post')], default=0),
        ),
        migrations.AddField(
            model_name='totocontent',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.IntegerField(choices=[(0, 'Live streaming'), (1, 'Others')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='players_k',
            field=models.ManyToManyField(related_name='events_k', to='core.Player'),
        ),
        migrations.AlterField(
            model_name='event',
            name='players_p',
            field=models.ManyToManyField(related_name='events_p', to='core.Player'),
        ),
        migrations.AddField(
            model_name='soccertoto',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soccer_toto', to='core.TotoContent'),
        ),
        migrations.AddField(
            model_name='soccertoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soccer_toto', to='core.Event'),
        ),
        migrations.AddField(
            model_name='quiztoto',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_toto', to='core.TotoContent'),
        ),
        migrations.AddField(
            model_name='quiztoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_toto', to='core.Event'),
        ),
        migrations.AddField(
            model_name='hackingtoto',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacking_toto', to='core.TotoContent'),
        ),
        migrations.AddField(
            model_name='hackingtoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacking_toto', to='core.Event'),
        ),
        migrations.AddField(
            model_name='esportstoto',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esports_toto', to='core.TotoContent'),
        ),
        migrations.AddField(
            model_name='esportstoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esports_toto', to='core.Event'),
        ),
        migrations.AddField(
            model_name='basketballtoto',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_toto', to='core.TotoContent'),
        ),
        migrations.AddField(
            model_name='basketballtoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketball_toto', to='core.Event'),
        ),
        migrations.AddField(
            model_name='baseballtoto',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseball_toto', to='core.TotoContent'),
        ),
        migrations.AddField(
            model_name='baseballtoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseball_toto', to='core.Event'),
        ),
        migrations.AddField(
            model_name='aitoto',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_toto', to='core.TotoContent'),
        ),
        migrations.AddField(
            model_name='aitoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_toto', to='core.Event'),
        ),
    ]
