# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170726_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='score_k',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='score_p',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
