# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170726_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=50)),
                ('size', models.IntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SupporterReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('nickname', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
                ('password', models.CharField(default='1234', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='totocontent',
            name='password',
            field=models.CharField(default='1234', max_length=12),
        ),
        migrations.AddField(
            model_name='supporter',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='core.SupporterReg'),
        ),
    ]
