# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170731_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supporter',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='totocontent',
            options={'ordering': ['-total', '-id']},
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='registry',
        ),
        migrations.AddField(
            model_name='aitoto',
            name='score_k',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitoto',
            name='score_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supporter',
            name='contact',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='supporter',
            name='password',
            field=models.CharField(default='1234', max_length=64),
        ),
        migrations.AlterField(
            model_name='esportstoto',
            name='score_k',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='esportstoto',
            name='score_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='student_id',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AlterField(
            model_name='totocontent',
            name='password',
            field=models.CharField(default='1234', max_length=64),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='SupporterReg',
        ),
    ]
