# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180726_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitoto',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='aitoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='baseballtoto',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='baseballtoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='basketballtoto',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='basketballtoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='esportstoto',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='esportstoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='hackingtoto',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='hackingtoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='quiztoto',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='quiztoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='soccertoto',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='soccertoto',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='score_weight',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='win_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='toto',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totos', to='core.TotoContent'),
        ),
        migrations.AlterField(
            model_name='toto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totos', to='core.Event'),
        ),
        migrations.DeleteModel(
            name='AIToto',
        ),
        migrations.DeleteModel(
            name='BaseballToto',
        ),
        migrations.DeleteModel(
            name='BasketballToto',
        ),
        migrations.DeleteModel(
            name='EsportsToto',
        ),
        migrations.DeleteModel(
            name='HackingToto',
        ),
        migrations.DeleteModel(
            name='QuizToto',
        ),
        migrations.DeleteModel(
            name='SoccerToto',
        ),
    ]
