# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180727_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='score_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='win_weight',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
