# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180727_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
                ('password', models.CharField(default='1234', max_length=64)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cheermessage',
            options={'ordering': ['likes', '-time']},
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='password',
        ),
        migrations.AddField(
            model_name='supporter',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supporter',
            name='sex',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0),
        ),
        migrations.AlterField(
            model_name='cheermessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.Location'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='members', to='core.SupporterTeam'),
        ),
    ]
