# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180827_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporterteam',
            name='contact',
        ),
        migrations.AddField(
            model_name='supporter',
            name='contact',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
